### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by ramunozp** [sciactive/pnotify#342] opened 2018-05-31 17:37 UTC
can you see a progress bar xon the time until the notification is closed?

![image](https://user-images.githubusercontent.com/24207310/40797920-b4187e70-64d7-11e8-9104-e549a2b6beae.png)

**Comment by hperrin** [comment] 2018-11-24 01:35
Duplicate of #303.

**Closed by hperrin** 2018-11-24 01:35 UTC
Labels: duplicate
