### ISSUE TITLE
[Confirm module]The black overlay is'nt removed when the history module isn't used

### ISSUE THREAD

**Issue by arsenalol69** [sciactive/pnotify#214] opened 2016-01-11 10:11 UTC
I found a bug when using the confirm module whitout the history module : when I close a Modal Confirm dialog, the black overlay isn't removed. After hours of searching, I've found that the objects inside the array PNotify.notices have the option destroy=true, and with I use the history module, this option is set to false.
So this part of code is executed and remove too early the object : 

```
if (that.options.destroy) {
   if (PNotify.notices !== null) {
      var idx = $.inArray(that,PNotify.notices);
       if (idx !== -1) {
          PNotify.notices.splice(idx,1);
       }
   }
}
```

Anyway, thanks for the great job you've done ! :)

**Comment by NightOwl888** [comment] 2016-01-30 11:43
I am closing #225 because it is an exact duplicate of this one. But do note that issue has a demo showing the problem.

**Closed** 2017-04-21 22:44 UTC
Labels: bug, in progress
