### ISSUE TITLE
Text display problem (IE8)

### ISSUE THREAD

**Issue by grantice** [sciactive/pnotify#144] opened 2014-07-15 08:02 UTC
Sorry for my bad English.
Maybe perseOptions have a bug, when I use this library on IE8.

The following display to text field
function(obj, start) { ...

I comment out following line, then ok.
this.options.text = curOpts

Please check this problem.
Thank you.

**Comment by pribilinskiy** [comment] 2015-03-22 23:03
+1
The issue is still there, in IE8

**Comment by wullinkm** [comment] 2015-03-23 08:43
Hi,

I'm not completely sure if the solution is correct but this seems to fix the problem in IE8:

In the function `parseOptions: function(options, moreOptions)` replace line 430 (PNotify PNotify 2.0.1):

`for (var curIndex in optArray) {`
with:
`for (var curIndex = 0; curIndex < optArray.length; curIndex++) {`

**Comment by mormsby** [comment] 2015-03-23 14:33
@wullinkm I did that exact change and it got merged into master

@pribilinskiy I agree with @wullinkm, maybe you don't have the latest version

Here is the commit folks https://github.com/sciactive/pnotify/commit/7a90c177afcfe11e5dc6cccc35dbc47ee1afc0c1

**Comment by wullinkm** [comment] 2015-03-23 15:18
@mormsby ah that explains it, I just downloaded the latest packaged release, which doesn't have the change yet :)

**Closed** 2018-01-31 03:26 UTC
Labels: bug, ready
