### ISSUE TITLE
Bug? Cannot use 'in' operator to search for 'close' in undefined

### ISSUE THREAD

**Issue by hozza** [sciactive/pnotify#256] opened 2016-07-28 18:41 UTC
I get the following error on Firefox & Safari & Chromium - Linux Mint and macOS... 

pnotify.js:38 Uncaught TypeError: Cannot use 'in' operator to search for 'close' in undefined
afterClose  @   pnotify.js:38
runModules  @   pnotify.js:8
(anonymous function)    @   pnotify.js:19
(anonymous function)    @   pnotify.js:22

I have the desktop module and callbacks module bundled. Anyone have any ideas? :S

**Comment by hperrin** [comment] 2018-01-25 19:28
Thanks for the report. I've found the cause. I'll put this in a bugfix release for the 3.2 line.

**Comment by hperrin** [comment] 2018-02-08 21:43
Fixed in the v3.2 branch.

**Closed by hperrin** 2018-02-08 21:43 UTC
Labels: bug, in progress
