### ISSUE TITLE
Bug? Desktop Fallback failure Linux Mint Firefox

### ISSUE THREAD

**Issue by hozza** [sciactive/pnotify#257] opened 2016-07-28 18:44 UTC
On Firefox 47.0 on Linux Mint 18 it will not trigger any desktop notifications or fall back to normal notifications? :S no error thrown or anything...

It does work with Chromium on same OS.

**Comment by hperrin** [comment] 2018-02-01 20:55
Duplicate of #256.

**Closed by hperrin** 2018-02-01 20:55 UTC
